version: '3.4'

services:
    inventorydb:
        image: mongo

    inventory.api:
        image: ${DOCKER_REGISTRY-}inventoryapi
        build:
            context: .
            dockerfile: Src/Services/Inventory/Inventory.API/Dockerfile
