version: '3.4'

services:
    inventorydb:
        container_name: inventorydb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"

    inventory.api:
        container_name: inventoryapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "OnlineMarketPlaceDbSettings:ConnectionString=mongodb://inventorydb:27017"
        depends_on:
            - inventorydb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "5000:80"